"""add user_id to budget

Revision ID: 1df185261bf8
Revises: 138fd661d14f
Create Date: 2024-07-18 20:15:35.547482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1df185261bf8'
down_revision = '138fd661d14f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('monthly_budget',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('tag_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_foreign_key('budget', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('tag_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('monthly_budget',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
