"""date column in income to string again

Revision ID: 34056790faa3
Revises: 2f38a07b5133
Create Date: 2024-07-21 08:19:29.010057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34056790faa3'
down_revision = '2f38a07b5133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.create_foreign_key('debt', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=False)

    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
