"""add foreignkey for category in income and expense

Revision ID: 3b89a2d140f4
Revises: 499601cfea4f
Create Date: 2024-07-18 11:45:21.213069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b89a2d140f4'
down_revision = '499601cfea4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('expense', 'category', ['category'], ['id'])

    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('income', 'category', ['category'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('income', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category')

    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category')

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
