"""db model for installments

Revision ID: 4b231a5bef39
Revises: 34056790faa3
Create Date: 2024-07-21 16:46:29.145213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b231a5bef39'
down_revision = '34056790faa3'
branch_labels = None
depends_on = None

def upgrade(migrate_engine):
    meta = MetaData(bind=migrate_engine)
    users = Table('users', meta, autoload=True)
    users.c.user_id.alter(name='id')

def downgrade(migrate_engine):
    meta = MetaData(bind=migrate_engine)
    users = Table('users', meta, autoload=True)
    users.c.id.alter(name='user_id')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('installments')
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.create_foreign_key('debt', 'persons', ['person'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.drop_constraint('debt', type_='foreignkey')
    op.drop_table('installments')
    # ### end Alembic commands ###
