"""installments table added 

Revision ID: 836d6b265d98
Revises: 4b231a5bef39
Create Date: 2024-07-21 20:52:39.208246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '836d6b265d98'
down_revision = '4b231a5bef39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('person', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=30), nullable=True),
    sa.Column('inst_num', sa.Integer(), nullable=False),
    sa.Column('inst_rate', sa.Integer(), nullable=True),
    sa.Column('first_date', sa.String(length=10), nullable=False),
    sa.Column('pay_period', sa.Integer(), nullable=False),
    sa.Column('inst_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['person'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_income')
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.create_foreign_key('debt', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.create_table('_alembic_tmp_income',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=20), nullable=False),
    sa.Column('person', sa.INTEGER(), nullable=True),
    sa.Column('tag_id', sa.INTEGER(), nullable=True),
    sa.Column('amount', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=30), nullable=False),
    sa.Column('category', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.id'], name='income'),
    sa.ForeignKeyConstraint(['person'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['username'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('installments')
    # ### end Alembic commands ###
