"""add date and pay_date to Debt and Credit

Revision ID: 987da8732cb3
Revises: eb0025f14a64
Create Date: 2024-07-20 21:46:14.281089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987da8732cb3'
down_revision = 'eb0025f14a64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('pay_date', sa.String(length=10), nullable=False))

    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('pay_date', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.drop_column('pay_date')
        batch_op.drop_column('date')

    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.drop_column('pay_date')
        batch_op.drop_column('date')

    # ### end Alembic commands ###
