"""fix amount in debt

Revision ID: c1e401966fe7
Revises: 7b4d17a0e141
Create Date: 2024-07-20 21:55:17.321546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1e401966fe7'
down_revision = '7b4d17a0e141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               nullable=False)
        batch_op.create_foreign_key('debt', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('amount',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
