"""remove tag from budget

Revision ID: e9b5c68ed2ac
Revises: 1df185261bf8
Create Date: 2024-07-18 20:23:25.093210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9b5c68ed2ac'
down_revision = '1df185261bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_constraint('budget', type_='foreignkey')
        batch_op.drop_column('tag_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'tags', ['tag_id'], ['id'])

    # ### end Alembic commands ###
