"""add text to Debt and Credit

Revision ID: eb0025f14a64
Revises: e9b5c68ed2ac
Create Date: 2024-07-20 21:14:13.989617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0025f14a64'
down_revision = 'e9b5c68ed2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.create_foreign_key("budget", 'user', ['user_id'], ['id'])

    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=30), nullable=False))

    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.String(length=30), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('debt', schema=None) as batch_op:
        batch_op.drop_column('debt')

    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.drop_column('credit')

    with op.batch_alter_table('budget', schema=None) as batch_op:
        batch_op.drop_constraint("budget", type_='foreignkey')

    # ### end Alembic commands ###
